### ISSUE TITLE
Fuel Sprites

### ISSUE THREAD

**Issue by Niyy** [SRJC-Computer-Science-Club/Ludum-Dare-38-Space-Junkies#2]
The fuel sprites need to be done differently (sorry Erick)
    - Doing it in the editor not the code is better
    - It is very hard to see (the sprite fuel is a good choice)

**Comment by LinnierGames** [comment]
Fuel will be drifting in space right? Or will it also be collectable on a planet? I'm just trying to figure out what size should the sprite be

**Comment by Niyy** [comment]
This is pertaining to the fuel bar at the top of the screen.

**Comment by LinnierGames** [comment]
Sounds good! :)
